/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yacht_android_augmentednavigation_Math3d */

#ifndef _Included_com_yacht_android_augmentednavigation_Math3d
#define _Included_com_yacht_android_augmentednavigation_Math3d
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yacht_android_augmentednavigation_Math3d
 * Method:    m3dGetPlaneEquationJni
 * Signature: ([F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_com_yacht_android_augmentednavigation_Math3d_m3dGetPlaneEquationJni
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     com_yacht_android_augmentednavigation_Math3d
 * Method:    m3dMakePlanarShadowMatrixJni
 * Signature: ([F[F[F)V
 */
JNIEXPORT void JNICALL Java_com_yacht_android_augmentednavigation_Math3d_m3dMakePlanarShadowMatrixJni
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
